-- Multi-promo, étape 1 : fondations (spec A et D.2). Purement additive : aucune règle
-- d'accès ne change, l'app actuelle fonctionne à l'identique.
-- Marche arrière : 20261001_multi_promo_1_fondations_retour.sql

-- 1. Lieux et promos -----------------------------------------------------------------
create table public.lieux (
  id integer generated by default as identity primary key,
  nom text not null unique,
  created_at timestamptz not null default now()
);
insert into public.lieux (id, nom) values (1, 'Nîmes'), (2, 'Montpellier');
alter table public.lieux alter column id restart with 3;

create table public.promos (
  id integer generated by default as identity primary key,
  lieu_id integer not null references public.lieux(id),
  nom text not null,
  date_debut date not null,
  date_fin date,
  created_at timestamptz not null default now()
);
insert into public.promos (id, lieu_id, nom, date_debut, date_fin) values
  (1, 1, 'Nîmes, mars 2026', '2026-03-30', '2026-12-11'),
  (2, 1, 'Nîmes, septembre 2026', '2026-09-30', null);
alter table public.promos alter column id restart with 3;

alter table public.lieux enable row level security;
alter table public.promos enable row level security;
revoke all on public.lieux, public.promos from anon;
revoke insert, update, delete, truncate on public.lieux, public.promos from authenticated;
grant update (nom) on public.promos to authenticated;

-- 2. Colonnes promo_id et lieu_id. Une valeur constante d'abord : aucune réécriture,
--    aucun trigger déclenché, aucun updated_at touché. Les défauts dynamiques suivent en 4.
alter table public.stagiaires         add column promo_id integer not null default 1 references public.promos(id);
alter table public.evaluations        add column promo_id integer not null default 1 references public.promos(id);
alter table public.evaluations_audit  add column promo_id integer not null default 1 references public.promos(id);
alter table public.passages           add column promo_id integer not null default 1 references public.promos(id);
alter table public.passages_audit     add column promo_id integer not null default 1 references public.promos(id);
alter table public.planning_entries   add column promo_id integer not null default 1 references public.promos(id);
alter table public.planning_half_meta add column promo_id integer not null default 1 references public.promos(id);
alter table public.planning_jours_off add column promo_id integer not null default 1 references public.promos(id);
alter table public.agenda_events      add column promo_id integer not null default 1 references public.promos(id);
alter table public.qcm_attempts       add column promo_id integer not null default 1 references public.promos(id);
alter table public.epcf_evaluations   add column promo_id integer not null default 1 references public.promos(id);
alter table public.epcf_livrets       add column promo_id integer not null default 1 references public.promos(id);
alter table public.dp_dossiers        add column promo_id integer not null default 1 references public.promos(id);
alter table public.fiches_suivi       add column promo_id integer not null default 1 references public.promos(id);
-- Réglages : promo_id nulle = réglage global (quota de l'assistant et deux clés inutilisées).
alter table public.settings           add column promo_id integer default 1 references public.promos(id);
update public.settings set promo_id = null where key in ('chatbot_quota_jour', 'cohort_name', 'password_hash');
-- Seules ces trois clés sont globales : sans promo, toute autre insertion est refusée.
alter table public.settings add constraint settings_globaux_prevus
  check (promo_id is not null or key in ('chatbot_quota_jour', 'cohort_name', 'password_hash'));

alter table public.benevoles      add column lieu_id integer not null default 1 references public.lieux(id);
alter table public.auto_ecoles    add column lieu_id integer not null default 1 references public.lieux(id);
alter table public.benevole_suivi add column lieu_id integer not null default 1 references public.lieux(id);

-- 3. Fonctions de contexte (spec B.2) ------------------------------------------------
create or replace function public.peut_acceder_promo(p integer)
returns boolean language sql stable security definer
set search_path to 'public', 'pg_temp'
as $$
  select exists (select 1 from promos pr where pr.id = p)
     and exists (
       select 1 from user_profiles up
       where lower(up.email) = lower((select auth.jwt() ->> 'email'))
         and (   up.is_founder
              or up.role in ('prof', 'admin')
              or exists (select 1 from stagiaires s
                          where s.id = up.stagiaire_id and s.promo_id = p))
     );
$$;

-- Promo par défaut : celle de la fiche stagiaire ; pour le personnel, la plus ancienne
-- promo encore en cours, à défaut la plus récente. Nulle sans utilisateur.
create or replace function public.promo_par_defaut()
returns integer language sql stable security definer
set search_path to 'public', 'pg_temp'
as $$
  with moi as (
    select up.stagiaire_id, (up.is_founder or up.role in ('prof', 'admin')) as tout_voir
    from user_profiles up
    where lower(up.email) = lower((select auth.jwt() ->> 'email'))
    limit 1
  )
  select coalesce(
    (select s.promo_id from moi join stagiaires s on s.id = moi.stagiaire_id),
    (select pr.id from promos pr, moi
      where moi.tout_voir and (pr.date_fin is null or pr.date_fin >= current_date)
      order by pr.date_debut, pr.id limit 1),
    (select pr.id from promos pr, moi
      where moi.tout_voir
      order by pr.date_debut desc, pr.id desc limit 1)
  );
$$;

-- Promo de la requête : l'en-tête x-promo-id s'il est accessible ; sans en-tête, la promo
-- par défaut ; en-tête interdit ou fantaisiste : nulle (aucune ligne, insertion refusée).
create or replace function public.promo_courante()
returns integer language plpgsql stable security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  brut text := nullif(current_setting('request.headers', true), '');
  entete text;
begin
  if brut is not null then
    -- En-têtes illisibles : aucune promo (PostgREST envoie toujours un JSON valide).
    if not pg_input_is_valid(brut, 'json') then
      return null;
    end if;
    entete := brut::json ->> 'x-promo-id';
  end if;
  if entete is null or entete = '' then
    return promo_par_defaut();
  end if;
  if entete ~ '^[0-9]{1,9}$' and peut_acceder_promo(entete::integer) then
    return entete::integer;
  end if;
  return null;
end;
$$;

create or replace function public.lieu_courant()
returns integer language sql stable security definer
set search_path to 'public', 'pg_temp'
as $$
  select pr.lieu_id from promos pr where pr.id = promo_courante();
$$;

create or replace function public.mes_promos()
returns table (id integer, nom text, lieu_id integer, lieu_nom text, date_debut date,
               date_fin date, par_defaut boolean, stagiaire_id integer)
language sql stable security definer
set search_path to 'public', 'pg_temp'
as $$
  select pr.id, pr.nom, pr.lieu_id, l.nom, pr.date_debut, pr.date_fin,
         coalesce(pr.id = d.pid, false),
         (select s.id from user_profiles up join stagiaires s on s.id = up.stagiaire_id
           where lower(up.email) = lower((select auth.jwt() ->> 'email')) and s.promo_id = pr.id
           limit 1)
  from promos pr
  join lieux l on l.id = pr.lieu_id
  cross join (select promo_par_defaut() as pid) d
  where peut_acceder_promo(pr.id)
  order by pr.date_debut, pr.id;
$$;

-- Sonde (supprimée à l'étape 2) : renvoie l'en-tête reçu, pour prouver qu'il traverse
-- la passerelle. Elle ne lit aucune donnée.
create or replace function public.diag_entete_promo()
returns text language sql stable
set search_path to 'public', 'pg_temp'
as $$
  select nullif(current_setting('request.headers', true), '')::json ->> 'x-promo-id';
$$;

revoke all on function public.peut_acceder_promo(integer), public.promo_par_defaut(),
  public.promo_courante(), public.lieu_courant(), public.mes_promos(),
  public.diag_entete_promo() from public;
grant execute on function public.peut_acceder_promo(integer), public.promo_par_defaut(),
  public.promo_courante(), public.lieu_courant() to anon, authenticated, service_role;
grant execute on function public.mes_promos() to authenticated, service_role;
revoke execute on function public.mes_promos() from anon;
grant execute on function public.diag_entete_promo() to anon, authenticated;

-- 4. Valeurs par défaut dynamiques
alter table public.stagiaires         alter column promo_id set default public.promo_courante();
alter table public.planning_entries   alter column promo_id set default public.promo_courante();
alter table public.planning_half_meta alter column promo_id set default public.promo_courante();
alter table public.planning_jours_off alter column promo_id set default public.promo_courante();
alter table public.agenda_events      alter column promo_id set default public.promo_courante();
alter table public.settings           alter column promo_id set default public.promo_courante();
alter table public.benevoles          alter column lieu_id  set default public.lieu_courant();
alter table public.auto_ecoles        alter column lieu_id  set default public.lieu_courant();
-- Colonnes imposées par trigger : plus de défaut.
alter table public.evaluations        alter column promo_id drop default;
alter table public.evaluations_audit  alter column promo_id drop default;
alter table public.passages           alter column promo_id drop default;
alter table public.passages_audit     alter column promo_id drop default;
alter table public.qcm_attempts       alter column promo_id drop default;
alter table public.epcf_evaluations   alter column promo_id drop default;
alter table public.epcf_livrets       alter column promo_id drop default;
alter table public.dp_dossiers        alter column promo_id drop default;
alter table public.fiches_suivi       alter column promo_id drop default;
alter table public.benevole_suivi     alter column lieu_id  drop default;

-- 5. La promo d'une ligne de suivi est toujours celle de son stagiaire
create or replace function public.imposer_promo_du_stagiaire()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  select s.promo_id into new.promo_id from public.stagiaires s where s.id = new.stagiaire_id;
  return new;
end;
$$;
create trigger trg_promo_du_stagiaire before insert or update on public.evaluations
  for each row execute function public.imposer_promo_du_stagiaire();
create trigger trg_promo_du_stagiaire before insert or update on public.passages
  for each row execute function public.imposer_promo_du_stagiaire();
create trigger trg_promo_du_stagiaire before insert or update on public.qcm_attempts
  for each row execute function public.imposer_promo_du_stagiaire();
create trigger trg_promo_du_stagiaire before insert or update on public.epcf_evaluations
  for each row execute function public.imposer_promo_du_stagiaire();
create trigger trg_promo_du_stagiaire before insert or update on public.epcf_livrets
  for each row execute function public.imposer_promo_du_stagiaire();
create trigger trg_promo_du_stagiaire before insert or update on public.dp_dossiers
  for each row execute function public.imposer_promo_du_stagiaire();
create trigger trg_promo_du_stagiaire before insert or update on public.fiches_suivi
  for each row execute function public.imposer_promo_du_stagiaire();

create or replace function public.imposer_lieu_du_benevole()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  select b.lieu_id into new.lieu_id from public.benevoles b where b.id = new.benevole_id;
  return new;
end;
$$;
create trigger trg_lieu_du_benevole before insert or update on public.benevole_suivi
  for each row execute function public.imposer_lieu_du_benevole();

create or replace function public.verifier_affiliation_meme_lieu()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if new.lieu_id is not null and new.auto_ecole_id is not null and not exists (
    select 1 from public.auto_ecoles a where a.id = new.auto_ecole_id and a.lieu_id = new.lieu_id
  ) then
    raise exception 'Cette auto-école appartient à un autre lieu.' using errcode = '23514';
  end if;
  return new;
end;
$$;
create trigger trg_affiliation_meme_lieu before insert or update on public.benevoles
  for each row execute function public.verifier_affiliation_meme_lieu();

-- 6. Historiques : la promo de la ligne auditée est recopiée
create or replace function public.audit_evaluations()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  who text := coalesce(auth.jwt()->>'email', 'anon');
begin
  if tg_op = 'INSERT' then
    insert into evaluations_audit(evaluation_id, action, after_data, changed_by_email, promo_id)
    values (new.id, 'insert', to_jsonb(new), who, new.promo_id);
    return new;
  elsif tg_op = 'UPDATE' then
    insert into evaluations_audit(evaluation_id, action, before_data, after_data, changed_by_email, promo_id)
    values (new.id, 'update', to_jsonb(old), to_jsonb(new), who, new.promo_id);
    return new;
  elsif tg_op = 'DELETE' then
    insert into evaluations_audit(evaluation_id, action, before_data, changed_by_email, promo_id)
    values (old.id, 'delete', to_jsonb(old), who, old.promo_id);
    return old;
  end if;
end;
$$;

create or replace function public.audit_passages()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  -- Le « who » client (prénom) est gardé, l'email du jeton le remplace s'il est présent.
  client_who text := coalesce(new.created_by_who, new.updated_by_who, old.created_by_who, old.updated_by_who, 'anon');
  jwt_email text := coalesce(auth.jwt()->>'email', null);
  who_trace text := case when jwt_email is null then client_who else jwt_email end;
begin
  if tg_op = 'INSERT' then
    insert into passages_audit(passage_id, action, after_data, changed_by_who, promo_id)
    values (new.id, 'insert', to_jsonb(new), who_trace, new.promo_id);
    return new;
  elsif tg_op = 'UPDATE' then
    insert into passages_audit(passage_id, action, before_data, after_data, changed_by_who, promo_id)
    values (new.id, 'update', to_jsonb(old), to_jsonb(new), who_trace, new.promo_id);
    return new;
  elsif tg_op = 'DELETE' then
    insert into passages_audit(passage_id, action, before_data, changed_by_who, promo_id)
    values (old.id, 'delete', to_jsonb(old), who_trace, old.promo_id);
    return old;
  end if;
end;
$$;

-- 7. Progression des thèmes et état des examens, propres à chaque promo
create table public.themes_progression (
  promo_id integer not null default public.promo_courante() references public.promos(id),
  theme_id integer not null references public.themes(id) on delete cascade,
  statut text not null default 'À faire' check (statut in ('À faire', 'En cours', 'Fait')),
  date_fait date,
  date_qcm date,
  notes text,
  updated_by_email text,
  updated_at timestamptz not null default now(),
  primary key (promo_id, theme_id)
);
create table public.qcm_examens (
  promo_id integer not null default public.promo_courante() references public.promos(id),
  qcm_id bigint not null references public.qcm(id) on delete cascade,
  published boolean not null default false,
  published_by_email text,
  published_at timestamptz,
  exam_nb_questions integer,
  exam_question_ids jsonb,
  exam_draw_mode text check (exam_draw_mode in ('random', 'manual')),
  exam_seconds_per_question integer not null default 30,
  exam_ferme_a timestamptz,
  updated_at timestamptz not null default now(),
  primary key (promo_id, qcm_id)
);
comment on column public.qcm_examens.published is
  'Examen ouvert pour la promo, PAS « QCM visible » : la lecture et l''entraînement n''en dépendent pas.';
alter table public.themes_progression enable row level security;
alter table public.qcm_examens enable row level security;
revoke all on public.themes_progression, public.qcm_examens from anon;
create trigger themes_progression_set_updated_at before update on public.themes_progression
  for each row execute function public.trigger_set_updated_at();
create trigger qcm_examens_set_updated_at before update on public.qcm_examens
  for each row execute function public.trigger_set_updated_at();

insert into public.themes_progression (promo_id, theme_id, statut, date_fait, date_qcm, notes, updated_by_email, updated_at)
select 1, t.id, t.statut, t.date_fait, t.date_qcm, t.notes, t.updated_by_email, coalesce(t.updated_at, now())
from public.themes t;
insert into public.qcm_examens (promo_id, qcm_id, published, published_by_email, published_at,
  exam_nb_questions, exam_question_ids, exam_draw_mode, exam_seconds_per_question, exam_ferme_a, updated_at)
select 1, q.id, q.published, q.published_by_email, q.published_at, q.exam_nb_questions,
  q.exam_question_ids, q.exam_draw_mode, q.exam_seconds_per_question, q.exam_ferme_a, q.updated_at
from public.qcm q;

-- 8. Synchronisation pendant la bascule (spec D.2), dans les deux sens, pour la promo 1
--    seulement. Supprimée à l'étape 5. Créée APRÈS la copie, qui ne doit rien déclencher.
create or replace function public.sync_themes_vers_progression()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if pg_trigger_depth() > 1 then return new; end if;
  insert into themes_progression (promo_id, theme_id, statut, date_fait, date_qcm, notes, updated_by_email)
  values (1, new.id, new.statut, new.date_fait, new.date_qcm, new.notes, new.updated_by_email)
  on conflict (promo_id, theme_id) do update
    set statut = excluded.statut, date_fait = excluded.date_fait, date_qcm = excluded.date_qcm,
        notes = excluded.notes, updated_by_email = excluded.updated_by_email;
  return new;
end;
$$;
create trigger trg_sync_themes_progression
  after insert or update of statut, date_fait, date_qcm, notes, updated_by_email on public.themes
  for each row execute function public.sync_themes_vers_progression();

create or replace function public.sync_progression_vers_themes()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if pg_trigger_depth() > 1 or new.promo_id <> 1 then return new; end if;
  update themes set statut = new.statut, date_fait = new.date_fait, date_qcm = new.date_qcm,
                    notes = new.notes, updated_by_email = new.updated_by_email
   where id = new.theme_id;
  return new;
end;
$$;
create trigger trg_sync_progression_themes after insert or update on public.themes_progression
  for each row execute function public.sync_progression_vers_themes();

create or replace function public.sync_qcm_vers_examens()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if pg_trigger_depth() > 1 then return new; end if;
  insert into qcm_examens (promo_id, qcm_id, published, published_by_email, published_at,
    exam_nb_questions, exam_question_ids, exam_draw_mode, exam_seconds_per_question, exam_ferme_a)
  values (1, new.id, new.published, new.published_by_email, new.published_at, new.exam_nb_questions,
    new.exam_question_ids, new.exam_draw_mode, new.exam_seconds_per_question, new.exam_ferme_a)
  on conflict (promo_id, qcm_id) do update
    set published = excluded.published, published_by_email = excluded.published_by_email,
        published_at = excluded.published_at, exam_nb_questions = excluded.exam_nb_questions,
        exam_question_ids = excluded.exam_question_ids, exam_draw_mode = excluded.exam_draw_mode,
        exam_seconds_per_question = excluded.exam_seconds_per_question,
        exam_ferme_a = excluded.exam_ferme_a;
  return new;
end;
$$;
create trigger trg_sync_qcm_examens
  after insert or update of published, published_by_email, published_at, exam_nb_questions,
    exam_question_ids, exam_draw_mode, exam_seconds_per_question, exam_ferme_a on public.qcm
  for each row execute function public.sync_qcm_vers_examens();

create or replace function public.sync_examens_vers_qcm()
returns trigger language plpgsql security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if pg_trigger_depth() > 1 or new.promo_id <> 1 then return new; end if;
  update qcm set published = new.published, published_by_email = new.published_by_email,
    published_at = new.published_at, exam_nb_questions = new.exam_nb_questions,
    exam_question_ids = new.exam_question_ids, exam_draw_mode = new.exam_draw_mode,
    exam_seconds_per_question = new.exam_seconds_per_question, exam_ferme_a = new.exam_ferme_a
   where id = new.qcm_id;
  return new;
end;
$$;
create trigger trg_sync_examens_qcm after insert or update on public.qcm_examens
  for each row execute function public.sync_examens_vers_qcm();

revoke all on function public.imposer_promo_du_stagiaire(), public.imposer_lieu_du_benevole(),
  public.verifier_affiliation_meme_lieu(), public.sync_themes_vers_progression(),
  public.sync_progression_vers_themes(), public.sync_qcm_vers_examens(),
  public.sync_examens_vers_qcm() from public, anon, authenticated;

-- 9. Nouvelles unicités, À CÔTÉ des anciennes (supprimées à l'étape 3) et index
alter table public.planning_entries   add constraint planning_entries_promo_unique
  unique (promo_id, semaine_lundi, day_index, half_day, slot, lane);
alter table public.planning_half_meta add constraint planning_half_meta_promo_unique
  unique (promo_id, semaine_lundi, day_index, half_day);
alter table public.planning_jours_off add constraint planning_jours_off_promo_unique
  unique (promo_id, semaine_lundi, day_index);
alter table public.stagiaires         add constraint stagiaires_promo_prenom_unique
  unique (promo_id, prenom);
alter table public.settings add column id bigint generated always as identity;
alter table public.settings add constraint settings_promo_key_unique unique nulls not distinct (promo_id, key);

create index evaluations_promo_idx       on public.evaluations (promo_id);
create index evaluations_audit_promo_idx on public.evaluations_audit (promo_id);
create index passages_promo_idx          on public.passages (promo_id);
create index passages_audit_promo_idx    on public.passages_audit (promo_id);
create index agenda_events_promo_idx     on public.agenda_events (promo_id);
create index qcm_attempts_promo_idx      on public.qcm_attempts (promo_id);
create index epcf_evaluations_promo_idx  on public.epcf_evaluations (promo_id);
create index epcf_livrets_promo_idx      on public.epcf_livrets (promo_id);
create index dp_dossiers_promo_idx       on public.dp_dossiers (promo_id);
create index fiches_suivi_promo_idx      on public.fiches_suivi (promo_id);
create index benevoles_lieu_idx          on public.benevoles (lieu_id);
create index auto_ecoles_lieu_idx        on public.auto_ecoles (lieu_id);
create index benevole_suivi_lieu_idx     on public.benevole_suivi (lieu_id);
create index promos_lieu_idx             on public.promos (lieu_id);
create index themes_progression_theme_idx on public.themes_progression (theme_id);
create index qcm_examens_qcm_idx         on public.qcm_examens (qcm_id);
